### ISSUE TITLE
Cannot build v1.0.0

### ISSUE THREAD

**Issue by Frank-NL** [caddy-dns/route53#1]
My main.go:

package main

import (
        caddycmd "github.com/caddyserver/caddy/v2/cmd"

        // plug in Caddy modules here
        _ "github.com/caddyserver/caddy/v2/modules/standard"
        _ "github.com/caddy-dns/route53"

)

func main() {
        caddycmd.Main()
}

go build results in:

go: finding module for package github.com/caddyserver/caddy/v2/modules/standard
go: finding module for package github.com/caddyserver/caddy/v2/cmd
go: finding module for package github.com/caddy-dns/route53
go: found github.com/caddy-dns/route53 in github.com/caddy-dns/route53 v1.0.0
go: found github.com/caddyserver/caddy/v2/cmd in github.com/caddyserver/caddy/v2 v2.0.0
go: github.com/caddy-dns/route53@v1.0.0 requires
        github.com/libdns/route53@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000

Even though it should be fixed in https://github.com/caddy-dns/route53/commit/7a9c68f4489d0dfaf5ca76df39d4c21a972ca9ac it is still looking for the wrong version.

What is going wrong here?

**Comment by mholt** [comment]
This happens if tags are changed/overwritten. @danlsgiga you'll need to release v1.0.1.

In the meantime, setting GOPROXY=direct should work around it, but it will be very slow.

**Comment by danlsgiga** [comment]
Shoot... TIL overwriting tags makes this kind of a mess!

`Do not delete version tags from your repo. If you find a bug or a security issue with a version, release a new version. If people depend on a version that you have deleted, their builds may fail. Similarly, once you release a version, do not change or overwrite it. The module mirror and checksum database store modules, their versions, and signed cryptographic hashes to ensure that the build of a given version remains reproducible over time.`

**Comment by danlsgiga** [comment]
@Frank-NL, thanks for reporting this issue and thanks @mholt for the tip on the fix. I just tagged v1.0.1 and this should be fixed now!

**Comment by Frank-NL** [comment]
Thanks for writing the module, can’t wait to test it!

**Comment by Frank-NL** [comment]
@danlsgiga @mholt 
"Certificate obtained successfully"

Great! Thanks again.
