### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by rayjlinden** [caddy-dns/route53#12]
Thanks for accepting my PR.  However, can you do a new release?

The v1.1.0 release is broken.  Master is now fixed but there is no tag for it.  So this module will still not work in xcaddy or really even in go...

All that is needed is for someone to tag what is currently on master with a new version number.

**Comment by mholt** [comment]
I am busy today, maybe @danlsgiga will have a chance before I do.

In the meantime there's absolutely no reason you can't use `master` or `cb329a5c3ab0a49b8e8fee1cccb3fa621ef1902b` (the latest commit, currently) to build from.

**Comment by danlsgiga** [comment]
Thanks for bringing this up @rayjlinden. I've tagged v1.1.1!
