### ISSUE TITLE
dependency of caddy v2.4.5 requires golang v1.16

### ISSUE THREAD

**Issue by cmawhorter** [caddy-dns/route53#18]
this module was updated to use caddy v2.4.5 as a dependency. as of caddy v2.4.4 (i think?), support for golang < 1.16 was dropped.  this module should probably at the very least have its min. go version set to 1.16 to match.

https://github.com/caddy-dns/route53/blob/77e77b24c5646d6b1dd36e1d36b6a094aca8e180/go.mod#L6

**Comment by aymanbagabas** [comment]
Fixed in https://github.com/caddy-dns/route53/releases/tag/v1.2.0
