### ISSUE TITLE
Use AWS Credentials from environment variables

### ISSUE THREAD

**Issue by giodamelio** [caddy-dns/route53#19]
Is it possible to use AWS credentials from the environment (`AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`) first if they exist?

I would be happy to make a PR if there are no issues with the idea.

**Comment by hairyhenderson** [comment]
According to the docs (see https://github.com/libdns/route53) these should already be supported... Does this not work?

**Comment by georanma** [comment]
Didnt work for me either. Ended up creating a file in my container on build filling the credentials in from my env. On local, Ive mounted in a file.
