### ISSUE TITLE
This module needs to use Provision()

### ISSUE THREAD

**Issue by mholt** [caddy-dns/route53#2]
The libdns/route53 package has a `NewSession()` method: https://github.com/caddy-dns/route53/blob/8c20bfe316fe951d1e99a6c326ecc387bda4a1d1/route53.go#L24-L30

The `New()` function should not perform any provisioning: https://pkg.go.dev/github.com/caddyserver/caddy/v2?tab=doc#ModuleInfo

The [`Provisioner` interface](https://pkg.go.dev/github.com/caddyserver/caddy/v2?tab=doc#Provisioner) should be implemented instead.

(Labelling as a bug since it violates the doc.)

**Comment by danlsgiga** [comment]
I was not aware of the Provisioner interface. Thanks for pointing that out. Much more elegant way for dealing with initialization / provisioning.

**Comment by mholt** [comment]
Cool, thanks!
