### ISSUE TITLE
Provider has no field or method NewSession

### ISSUE THREAD

**Issue by eth-limo** [caddy-dns/route53#21]
I created a [fork](https://github.com/eth-limo/caddy-dns-route53) of `libdns/route53` in order to test some of the recent bug fixes (https://github.com/libdns/route53/issues/7, https://github.com/libdns/route53/pull/12) and I ran across this error:

```
/go/pkg/mod/github.com/eth-limo/caddy-dns-route53@v1.1.5/route53.go:35:10: p.NewSession undefined (type *Provider has no field or method NewSession)
```

For testing purposes I pinned `libdns/route53` to [v1.2.1-0.20220707195619-cc1414081972](https://github.com/libdns/route53/commit/122ecafb94cdde87fd8260aac4668fd261062c9e) which includes an upgrade to the AWS SDK and a few other fixes.

I'm building Caddy with the following command:

```
go get github.com/caddyserver/xcaddy/cmd/xcaddy && \
    xcaddy build v2.5.1 \
      --with github.com/eth-limo/caddy-dns-route53@v1.1.5
```

I'm assuming this will be an issue once this project upgrades `libdns/route53` to `v1.2.1`.

Thanks!

**Comment by aymanbagabas** [comment]
@eth-limo checkout the `upgrade` branch. I'm still testing it out.

**Comment by aymanbagabas** [comment]
@eth-limo tested the `upgrade` branch and was able to generate certificates. I'll make a release and close related issues.
