### ISSUE TITLE
Module not working or I'm dumb

### ISSUE THREAD

**Issue by rhferreira** [caddy-dns/route53#23]
Hello Guys, how are you?
We are facing a problem with the Route53 module.
After install the module and configuring it, we are receiving the following error message when we run the system status caddy:

Our configs / Code inside the Caddyfile:

*.example.com {
    tls {
        dns route53 {
            max_retries 10
        }
    }
    reverse_proxy {
        to http://target.example.com
    }
}

Then we reload the service (or even reboot the machine) and now we receive the following error message after sudo systemctl status caddy:

Jul 19 20:49:29 caddy[1827]: {"level":"error","ts":1658263769.5214586,"logger":"tls.obtain","msg":"could not get certificate from issuer","identifier":"*.domain.com","issuer":"acme-staging-v02.api.letsencrypt.org-directory","error":"[*.domain.com] solving challenges: presenting for challenge: adding temporary record for zone domain.com.: operation error Route 53: ListHostedZonesByName, failed to sign request: failed to retrieve credentials: static credentials are empty (order=https://acme-staging-v02.api.letsencrypt.org/acme/order/61399564/3266863684) (ca=https://acme-staging-v02.api.letsencrypt.org/directory)"}

Ps. I'm opening an issue because it used to work in our lab and this is a new environment and I don't know if the new version has any issue or (probably) I'm doing something wrong.

Thanks,
Rodolfo

**Comment by aymanbagabas** [comment]
This is related to https://github.com/libdns/route53/issues/13

**Comment by aymanbagabas** [comment]
@rhferreira please try the latest version https://github.com/caddy-dns/route53/releases/tag/v1.2.1

**Comment by rhferreira** [comment]
It worked!

**Comment by rhferreira** [comment]
Thanks a lot!
