### ISSUE TITLE
Error during install module

### ISSUE THREAD

**Issue by zakabluk** [caddy-dns/route53#32]
This is steps for reproduce.
1 docker run -it caddy:2.4.6-builder-alpine ash
2 xcaddy build   --with github.com/caddy-dns/route53
result
```
go get: added google.golang.org/protobuf v1.27.1
2023/03/14 07:17:14 [INFO] exec (timeout=0s): /usr/local/go/bin/go get -d -v github.com/caddy-dns/route53
github.com/caddy-dns/route53 imports
	github.com/caddyserver/caddy/v2 imports
	net/netip: package net/netip is not in GOROOT (/usr/local/go/src/net/netip)
```

**Comment by mholt** [comment]
Make sure you're using a recent version of Go. (netip was added within the last ~2 years or so). Caddy requires Go 1.19+.
