### ISSUE TITLE
[bug]: Deprecated AWSProfile field on config

### ISSUE THREAD

**Issue by erbesharat** [caddy-dns/route53#7]
It seems like that `github.com/libdns/route53` which uses `github.com/aws/aws-sdk-go/service/route53 (*r53.Route53)` has removed the AWSProfile field so copying the example from README doesn't work anymore.

**Comment by PhoenixPeca** [comment]
Hi @erbesharat , this is neither a bug nor a deprecated feature/field..

The AWSProfile field is an added feature in a yet-to-be-released version of caddy-dns.. you are looking at the README of the master branch.. For actual docs, please read the documentation in https://caddyserver.com/ or at the README of the [last release](https://github.com/caddy-dns/route53/releases/tag/v1.0.2)

**Comment by danlsgiga** [comment]
This should be fixed now that #4 has been merged.
